name: Create Journal Entry

on:
  #   push:
  #     branches: [ master ]
  #   pull_request:
  #     branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types: [create-entry]
  schedule:
    # EST is 5 hours behind UTC so this should trigger at 12 AM EST
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache deps
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            node_modules
            .shadow-cljs
            ~/.cache
            ~/.m2/repository
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-shadow-${{ hashFiles('**/*.manifest') }}
          restore-keys: |
            ${{ runner.os }}-modules-


      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
          cache: yarn
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: yarn.lock

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Journal Entry
        run: yarn braincore create-entry
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          SLACK_API_KEY: ${{ secrets.SLACK_API_KEY }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
